name       : ladspa
version    : '1.15'
release    : 2
source     :
    - https://www.ladspa.org/download/ladspa_sdk_1.15.tgz : 4229959b09d20c88c8c86f4aa76427843011705df22d9c28b38359fd1829fded
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Linux Audio Developer's Simple Plugin API
description: |
    Linux Audio Developer's Simple Plugin API
setup      : |
    %patch -Np0 < $pkgfiles/fix-memleak-in-plugin-scanning.patch
    sed -e "s#-O3#%CFLAGS% %LDFLAGS% -ldl#" -i src/Makefile
    sed -e "s#-Wl#-Wl,--no-as-needed#" -i src/Makefile
build      : |
    cd src
    %make targets
install    : |
    cd src
    %make_install INSTALL_BINARY_DIR="$installdir/usr/bin/" \
                  INSTALL_INCLUDE_DIR="$installdir/usr/include/" \
                  INSTALL_PLUGINS_DIR="$installdir/%libdir%/ladspa"
