name       : ladspa
version    : '1.17'
release    : 3
source     :
    - http://www.ladspa.org/download/ladspa_sdk_1.17.tgz : 27d24f279e4b81bd17ecbdcc38e4c42991bb388826c0b200067ce0eb59d3da5b
homepage   : https://www.ladspa.org/
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Linux Audio Developer's Simple Plugin API
description: |
    Linux Audio Developer's Simple Plugin API
setup      : |
    %patch -Np0 < $pkgfiles/fix-memleak-in-plugin-scanning.patch
    sed -e "s#-O3#%CFLAGS% %LDFLAGS% -ldl#" -i src/Makefile
    sed -e "s#-Wl#-Wl,--no-as-needed#" -i src/Makefile
builddeps  :
    - pkgconfig(sndfile)
build      : |
    cd src
    %make targets
install    : |
    cd src
    %make_install \
        INSTALL_BINARY_DIR="$installdir/usr/bin/" \
        INSTALL_INCLUDE_DIR="$installdir/usr/include/" \
        INSTALL_PLUGINS_DIR="$installdir/%libdir%/ladspa"
