name       : ladspa
version    : 1.13
release    : 1
source     :
    - https://github.com/OpenMandrivaAssociation/ladspa/raw/master/ladspa_sdk_1.13.tgz : b5ed3f4f253a0f6c1b7a1f4b8cf62376ca9f51d999650dd822650c43852d306b
license    : LGPL-2.0
summary    : Linux Audio Developer's Simple Plugin API
description: |
    Linux Audio Developer's Simple Plugin API
build      : |
    cd src
    %patch -Np1 < $pkgfiles/fix-memleak-in-plugin-scanning.patch
    %patch -Np2 < $pkgfiles/fallback-ladspa-path.patch
    sed -e 's/mkdirhier/mkdir -p/' \
        -e "s#-O3#%CFLAGS% %LDFLAGS% -ldl#" \
        -i makefile
    sed -e "s#-Wl#-Wl,--no-as-needed#" \
        -i makefile
    %make targets
install    : |
    cd src
    %make_install INSTALL_BINARY_DIR="$installdir/usr/bin/" \
        INSTALL_INCLUDE_DIR="$installdir/usr/include/" \
        INSTALL_PLUGINS_DIR="$installdir/%libdir%/ladspa"
